spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 54767115914-gcla0mork6h3156h4qcutjerm0mdf4fu.apps.googleusercontent.com
            client-secret: 비밀키
            scope: profile,email