spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/4mzbe?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: 4mzbe
    password: 4mzbe123!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
      show_sql: true
    defer-datasource-initialization: true

    profiles:
      include: oauth