spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 61017715467-fol81gb1mnmkcoh3tldgi79t2pn35lvh.apps.googleusercontent.com
            client-secret: fmzbe123!
            scope: profile,email